# Use uma imagem base leve do Python
FROM python:3.10-slim

# Atualize o apt-get e instale dependências do sistema:
# gcc para compilar, libgl1-mesa-glx e libglib2.0-0 para bibliotecas gráficas
RUN apt-get update && \
    apt-get install -y gcc libgl1-mesa-glx libglib2.0-0 && \
    apt-get clean

# Desativa a exigência de hash
ENV PIP_REQUIRE_HASHES=0

# Defina o diretório de trabalho
WORKDIR /app

# Copie o arquivo de dependências e instale as dependências Python
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copie todo o código do microserviço para o container
COPY . .

# Exponha a porta que o FastAPI usará (8000)
EXPOSE 8000

# Comando para iniciar o servidor FastAPI usando uvicorn
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
